language: python

git:
  depth: false

python:
  - "3.5"
  - "3.6"

jobs:
  include:
    # special deploy stage for tag builds ONLY
    - stage: deploy
      if: tag IS present
      script: skip
      after_script: skip
      deploy:
        provider: pypi
        user: "${PYPI_USERNAME}"
        password: "${PYPI_PASSWORD}"
        on:
          tags: true

install:
  - pip install .[all]
  - pip install .[dev]
  - pip install coveralls codacy-coverage

script:
  - scripts/travisci/check_precommit.sh
  - flake8 --version
  - flake8 src
  - flake8 --exclude=src,docs --extend-ignore=D
  - pytest --cov=akro

after_script:
  - coverage xml
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
